version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=address_ts
    volumes:
      - ./address_syn_dict.syn:/usr/share/postgresql/16/tsearch_data/address_syn_dict.syn
      - ./csv:/csv
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5000:5432"
